switched to rmardown
rmarkdown::render("PA1_template.Rmd")

error using knitr2html

knit2html("PA1_template.Rmd", ouput = "PA1_template.md" )
Error: It seems you should call rmarkdown::render() instead of knitr::knit2html() because PA1_template.Rmd appears to be an R Markdown v2 document.